spring.application.name=AichatBot

# Correct properties for Google AI Studio (API Key approach)
langchain4j.google-ai-gemini.chat-model.api-key=AIzaSyD8p6HMMenjLRk7itBDVEOPSbiH4MFoKWI
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.5-flash


# Disable the specific Spring AI auto-configs that are crashing your app
# Google Cloud Project ID
spring.ai.vertex.ai.gemini.project-id=

# Google Cloud Region
spring.ai.vertex.ai.gemini.location=us-central1

# Chat Model
spring.ai.vertex.ai.gemini.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.response-timeout=120s
spring.ai.vertex.ai.gemini.chat.options.connect-timeout=120s
spring.ai.vertex.ai.gemini.chat.options.temperature=0.2

# Embedding Model
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.embedding.text.options.model=gemini-embedding-001



server.port=2020
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5434/chat
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=user
spring.jpa.show-sql=true
logging.level.org.springframework.web=debug
logging.level.org.hibernate=debug
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.ai.vertex.ai.gemini.enabled=false
